apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: gate-app
  namespace: default
  labels:
    team: default
spec:
  selector:
    matchLabels:
      app: gate
  endpoints:
  - port: web
    path: /prometheusMetrics
